-- Замените значения YOUR_DATABASE_NAME, YOUR_DATABASE_USER и CHANGE_ME
-- перед выполнением этого файла.

CREATE DATABASE IF NOT EXISTS YOUR_DATABASE_NAME
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'YOUR_DATABASE_USER'@'localhost'
    IDENTIFIED BY 'CHANGE_ME';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
    ON YOUR_DATABASE_NAME.* TO 'YOUR_DATABASE_USER'@'localhost';

FLUSH PRIVILEGES;
